# Generated by Django 4.0.1 on 2022-02-04 03:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookingdatefrom', models.DateField(default='', max_length=100)),
                ('bookingdateto', models.DateField(default='', max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='seller_tb',
            old_name='sname',
            new_name='s_email',
        ),
        migrations.RenameField(
            model_name='seller_tb',
            old_name='uname',
            new_name='s_name',
        ),
        migrations.RemoveField(
            model_name='user_tb',
            name='booking_id',
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='s_password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='s_phone_no',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='s_username',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.CreateModel(
            name='product_tb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(default='', max_length=10)),
                ('dis', models.CharField(default='', max_length=100)),
                ('price', models.CharField(default='', max_length=10000)),
                ('img', models.FileField(default='', upload_to='images')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eapp.seller_tb')),
            ],
        ),
    ]
