# Generated by Django 4.0.1 on 2022-02-02 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_booking_tb_product_tb_remove_user_tb_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tb',
            old_name='pname',
            new_name='p_name',
        ),
        migrations.RenameField(
            model_name='seller_tb',
            old_name='sname',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='seller_tb',
            old_name='uname',
            new_name='s_name',
        ),
        migrations.AddField(
            model_name='product_tb',
            name='discreption',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='product_tb',
            name='product_image',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='s_password',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='s_phone',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='seller_tb',
            name='s_username',
            field=models.CharField(default='', max_length=10),
        ),
    ]
