# Generated by Django 4.0.1 on 2022-02-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0002_rename_sname_seller_tb_s_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_tb',
            name='status',
            field=models.CharField(default='', max_length=100),
        ),
    ]
