# Generated by Django 4.0.1 on 2022-02-02 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_rename_pname_product_tb_p_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_tb',
            old_name='email',
            new_name='s_email',
        ),
    ]
