# Generated by Django 4.0.1 on 2022-02-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_booking_tb_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_tb',
            name='s_email',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='seller_tb',
            name='s_phone_no',
            field=models.CharField(default='', max_length=12),
        ),
        migrations.AlterField(
            model_name='user_tb',
            name='phone_no',
            field=models.CharField(default='', max_length=12),
        ),
    ]
