# Generated by Django 4.0.1 on 2022-02-14 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_alter_seller_tb_s_email_alter_seller_tb_s_phone_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller_tb',
            name='authN',
            field=models.CharField(default='', max_length=100),
        ),
    ]
