# Generated by Django 4.0.1 on 2022-02-02 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_rename_email_seller_tb_s_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='seller_tb',
            old_name='s_phone',
            new_name='s_phone_no',
        ),
    ]
