# Generated by Django 4.0.1 on 2022-02-02 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0005_rename_s_phone_seller_tb_s_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='price',
            field=models.CharField(default='', max_length=10),
        ),
    ]
