# Generated by Django 4.0.1 on 2022-02-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0006_product_tb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='img',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
