# Generated by Django 4.0.1 on 2022-02-02 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_product_tb_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='discreption',
        ),
        migrations.RemoveField(
            model_name='product_tb',
            name='product_image',
        ),
    ]
