# Generated by Django 4.0.1 on 2022-02-26 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0007_booking_tb_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_tb',
            name='price',
        ),
    ]
