# Generated by Django 4.0.1 on 2022-04-06 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0008_remove_booking_tb_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller_tb',
            name='s_password',
            field=models.TextField(default='', max_length=100),
        ),
    ]
