# Generated by Django 4.0.1 on 2022-02-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0009_product_tb_discreption'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_tb',
            name='discreption',
        ),
        migrations.AlterField(
            model_name='product_tb',
            name='price',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
