# Generated by Django 4.0.1 on 2022-02-02 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0010_remove_product_tb_discreption_alter_product_tb_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_tb',
            name='discreption',
            field=models.CharField(default='', max_length=100),
        ),
    ]
