# Generated by Django 4.0.1 on 2022-02-02 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0011_product_tb_discreption'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_tb',
            old_name='discreption',
            new_name='dis',
        ),
    ]
