# Generated by Django 4.0.1 on 2022-02-03 22:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0013_product_tb_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_tb',
            name='booking',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='pid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eapp.product_tb'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='uid',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eapp.user_tb'),
            preserve_default=False,
        ),
    ]
