# Generated by Django 4.0.1 on 2022-02-03 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0014_booking_tb_booking_booking_tb_pid_booking_tb_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_tb',
            name='booking',
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='bookingdatefrom',
            field=models.DateField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='bookingdateto',
            field=models.DateField(default='', max_length=100),
        ),
    ]
