# Generated by Django 4.0.1 on 2022-02-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0015_remove_booking_tb_booking_booking_tb_bookingdatefrom_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_tb',
            name='pid',
        ),
        migrations.RemoveField(
            model_name='booking_tb',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='product_tb',
            name='sid',
        ),
    ]
