# Generated by Django 4.0.1 on 2022-02-03 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0017_product_tb_sid'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_tb',
            name='pid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eapp.product_tb'),
            preserve_default=False,
        ),
    ]
