# Generated by Django 4.0.1 on 2022-02-03 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0019_remove_booking_tb_pid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_tb',
            name='bookingdatefrom',
        ),
        migrations.RemoveField(
            model_name='booking_tb',
            name='bookingdateto',
        ),
    ]
