# Generated by Django 4.0.1 on 2022-02-03 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0020_remove_booking_tb_bookingdatefrom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_tb',
            name='bookingdatefrom',
            field=models.DateField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='booking_tb',
            name='bookingdateto',
            field=models.DateField(default='', max_length=100),
        ),
    ]
