# Generated by Django 4.0.1 on 2022-02-03 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0021_booking_tb_bookingdatefrom_booking_tb_bookingdateto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_tb',
            name='p_name',
            field=models.CharField(default='', max_length=10),
        ),
    ]
